version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: ndjan-soko-postgres
    environment:
      POSTGRES_DB: ndjansoko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
